export const poems = [
  {
    "id": 1,
    "title": "7 Stages of Love",
    "author": "dhanavan",
    "preview": "7 Stages of Love Our eyes meet, a fleeting gaze,...",
    "content": "7 Stages of Love\nOur eyes meet, a fleeting gaze,\nStuck in the void of Oblivion\u2019s haze.\nThe first step in love\u2019s gentle art,\nAttraction \u2013 where it all must start.\n\nWe yearn for moments, crave the thrill,\nSmirks and laughter, time stands still.\nThe second spark ignites the flame,\nInfatuation \u2013 love by another name.\n\nWe confess, hearts stripped of fear,\nOur journey begins, sincere and clear.\nThe third bond, a sacred dove,\nLove \u2013 the truest stage above.\n\nWe linger, share secrets untold,\nDreams and stories in each other\u2019s hold.\nThe fourth embrace, unwavering trust,\nTrust \u2013 the foundation of us.\n\nWe cherish, respect, and always care,\nDevotion blossoms in love we share.\nThe fifth hymn, where souls conspire,\nWorship \u2013 a love that lifts us higher.\n\nYour smile, your presence, a beacon bright,\nMiles dissolve in love\u2019s pure light.\nThe sixth storm, a reckless fire,\nMadness \u2013 passion\u2019s fierce desire.\n\nNo longer I, no longer you,\nTogether, eternal, our story true.\nThe seventh stage, where time takes breath,\nDeath \u2013 love\u2019s victory over death.",
    "emotion": "passion",
    "depth": 1,
    "theme": "Love & Romance",
    "volume": "Volume I: Echoes of the Heart"
  },
  {
    "id": 2,
    "title": "A Boy and a Coin",
    "author": "dhanavan",
    "preview": "A Boy and a Coin A poor mother gave her son a penny...",
    "content": "A Boy and a Coin\nA poor mother gave her son a penny,\n\u201cJust enough\u201d, she smiled, \u201cfor a treat, if any.\u201d\nHe held it close, a treasure so bright,\nA little golden star, his heart\u2019s delight.\n\nOff to the shop, he skipped with glee,\nBut the coin slipped, rolled to a tree.\nInto the grass, lost from the sight,\nBut nature stirred with magic that night.\n\nA squirrel peeked out, quick and spry,\nIt nudged the coin with a curious eye.\nDaisies leaned in, their petals glow,\nGuiding the coin where the soft winds blow.\n\nA fish in the brook flicked it high,\nAnd a robin swooped down from the sky.\nThe boy caught the coin with joy anew,\nA small bit of magic, a blessing so true.",
    "emotion": "mystery",
    "depth": 0.47,
    "theme": "Nature & Beauty",
    "volume": "Volume II: Nature's Breath"
  },
  {
    "id": 3,
    "title": "A Dream",
    "author": "dhanavan",
    "preview": "A Dream As I woke up, I heard a voice of a girl,...",
    "content": "A Dream\nAs I woke up, I heard a voice of a girl,\nPlaying with her toy,\nIn the backyard of the home,\n\nAs I looked her face,\nFound it was familiar to me, \nShe called me dad,\nAnd she said \u201cCome and play with me papa\u201d.\n\nI heard a another voice,\nRight behind me that whisper\u2019s,\n\u201cHoney, are you awake\u201d\n I found out,\nIt was you in and yet surprised,\nWe are married,\nAs we talked about having a baby girl,\nAnd it was happening,\nRight in front of me.\n\nI still can\u2019t believe,\nYou are mine and,\nI\u2019m yours,\nI wish it could me real;\n\nHeard an alarm sound,\nAnd found out, it wasn\u2019t real,\nIt was just a dream,\nA beautiful dream",
    "emotion": "mystery",
    "depth": 0.48,
    "theme": "Hope & Inspiration",
    "volume": "Volume III: The Human Experience"
  },
  {
    "id": 4,
    "title": "A Magic",
    "author": "dhanavan",
    "preview": "A Magic Art embraces the audience,...",
    "content": "A Magic\nArt embraces the audience,\nTo creates an awe;\n\nThat awe made on me,\nWhen you walked past through the window,\nChit-chatting with an unguarded tone,\n\nThat awe returned,\nWhen you walked past me,\nAnd gazed at me.\n\nYour thirst was quenched,\nThe water bottle you asked for from me.\n\nMy water bottle becomes magic,\nWhen your lips touched its rim;\n\nThe big-bang theory is magic,\nNewton\u2019s theories are magic,\nThe entire galaxies in the vast space are magic,\nThe existence of mankind is magic,\nAnimals, birds, and flowers, \nRivers, oceans, skies,\nMountains, valleys;\nAll these existence are some sort of awe!\n\nThe real awe is a magic,\nAnd that magic is YOU!",
    "emotion": "mystery",
    "depth": 1,
    "theme": "Nature & Beauty",
    "volume": "Volume II: Nature's Breath"
  },
  {
    "id": 5,
    "title": "A Stray cat and the Last Meal",
    "author": "dhanavan",
    "preview": "A Stray Cat and the Last Meal A fluffy, small, ...",
    "content": "A Stray Cat and the Last Meal\nA fluffy, small, \nCute little four-legged soul,\nOld, seeking warmth\u2014\nAnd something to fill a hungry belly.\n\nLost in the town,\nChased and beaten by shopkeepers,\nAbandoned by the one it once loved.\nWandering the alley walls,\nCraving affection, craving scraps.\n\nIt waits across the bustling restaurant,\nIn the heart of the city,\nHoping the waiters will toss away\nThe final bits of chopped fish.\nSurrounded by barking street dogs,\nIt shivers,\nThen flees to the town hall\u2019s edge.\n\nSwollen legs, bruised face,\nFolded ears, hunter\u2019s eyes\u2014\nReady to dash, to dream,\nTo open wings and fly beyond.\n\nAt last, a final piece is thrown,\nClutched in its mouth,\nIt sprints, hides beneath a bush.\n\nEats the last meal,\nSleeps the last sleep\u2014\nWakes up in heaven.",
    "emotion": "passion",
    "depth": 0.45,
    "theme": "Love & Romance",
    "volume": "Volume I: Echoes of the Heart"
  },
  {
    "id": 6,
    "title": "Admire from afar",
    "author": "dhanavan",
    "preview": "Admire from afar The presence loud, yet peace withi...",
    "content": "Admire from afar\nThe presence loud, yet peace within,\nTemple bells, a calming hymn.\n\nShooting stars, a silent awe,\nFrozen in their timeless draw.\n\nEach day feels like a moonlit sky,\nSoft and bright, where shadows lie.\n\nSunrise glows on oceans face,\nRippling light, a radiant grace,\nFrom afar, the sea seems fierce and wide,\nYet near, it's beauty lights and tide.",
    "emotion": "serenity",
    "depth": 1,
    "theme": "Nature & Beauty",
    "volume": "Volume II: Nature's Breath"
  },
  {
    "id": 7,
    "title": "Am I Well",
    "author": "dhanavan",
    "preview": "Am I Well? I don\u2019t feel well....",
    "content": "Am I Well?\nI don\u2019t feel well.\nMy mind is screaming\nVoices in my head\u2014haunting me,\nA full recap of all I did,\t\nAnd all I didn\u2019t.\n\nCareer, friends, and the connections I\u2019ve made\u2014\nNow questioning me,\nBetrayed.\nCornered and crooked in the dimming light.\nLove and relationships\u2014the worst part.\nTaken for granted, trash cans.\nThe efforts I made?\nJust a topic in her friends\u2019 gossips.\n\nWondering\u2026\nWhy was I made this way?\nQuestioning my very existence\u2014why all of this?\nThe room is filled with haunting shadows of the past,\nMy soul screams beneath an ocean of darkness.\nBlinded. Rustled. Bruised.\nRunning for so long through this dark room,\nAnd no shining door to escape through.\n\nA sad, sad symphony plays, \nUnraveling a city of lost hopes\nAnd unanswered prayers.\nI can\u2019t see anything in there.\nJust hopeless, slow music in my mind,\nInterrupted by\nVoiceless cries\u2026\nI can\u2019t feel anything\u2014\nNot even me.",
    "emotion": "melancholy",
    "depth": 0.39,
    "theme": "Hope & Inspiration",
    "volume": "Volume III: The Human Experience"
  },
  {
    "id": 8,
    "title": "Ashes to Dawn",
    "author": "dhanavan",
    "preview": "From Ashes, a New Dawn In the tempest of my days,Lo...",
    "content": "From Ashes, a New Dawn\nIn the tempest of my days,Love drifts like an autumn leaf\u2014Fleeting, golden, then gone,And I, the wind-torn branch.\nI dream of love, yet fear its weight,For in its grasp, I vanish.A soul poured empty, a well run dry,An echo in a hollow hall.\nOnce, love was a shattered mirror\u2014Fragments reflecting all but me.Once, love was a siren\u2019s song\u2014Sweet to the ear, deaf to my cries.\nSo I fell\u2014Like a star forsaking the sky,Like embers fading to coal.Memories clung like ivy,Their roots deep in time.\nBut then\u2014A dawn broke through the ruin,With hands of light and golden fire.She was no mere angel,But the sun upon a midnight sea.\nStep by step, she unchained the past,Led me from shadow into day.No longer a ghost in my own tale,I walked beside her, whole again.\nFrom silence to song,From ashes to dawn,I learned to love, to live,To breathe beyond the night.",
    "emotion": "passion",
    "depth": 0.69,
    "theme": "Love & Romance",
    "volume": "Volume I: Echoes of the Heart"
  },
  {
    "id": 9,
    "title": "Balcony and a Sunset",
    "author": "dhanavan",
    "preview": "A Balcony and a Sunset I woke after a long sleep,...",
    "content": "A Balcony and a Sunset\nI woke after a long sleep,\nwith a hot cup of coffee in my hand\u2014\nstanding in the balcony,\nstaring at the evening orange sunset.\n\nMy mind begins to fill with\u2014\nsome strange thoughts.\n\nLove, and the kind of relationships\u2014\nThey aren\u2019t easy at all,\nYou have to work on them,\nspend time and efforts.\n\nTalking about relationships...\nletting go holds dimensions of pain.\nThere is a death,\nand also,\na morning sunrise in letting go.\n\nHappiness\u2014\nYou can find in different ways,\nfrom different people,\n\nSometimes, it hides in:\ngiving gifts, receiving gifts,\nshowing and offering love,\nreceiving love, helping people,\ncaring, hugging, playful teasing,\nspending for the ones you love. \n\nAnd also\u2014\nSometimes,\nhappiness flows out from the eyes:\ninaudible, voiceless, silent tears\u2014\nunveiled feelings.\n\nHorrible?\nLife is strange,\nSometimes, too strange.\nHolding on to the past\nfeels like yapping about an unseen ghost.\n\nLife is strange,\nbecause strangers are strange.\nStrangers become friends,\nThe most trusted ones, partners...\nAnd sometimes lovers.\n\nSeeking the red string\u2014\nYet never found it,\nSo I decided to chase the sun and stars,\nIn the mid skies of day and night.\n\nListening to those thoughts,\nmy cup becomes empty.\nAs so\u2014\nready to refill.",
    "emotion": "passion",
    "depth": 0.36,
    "theme": "Nature & Beauty",
    "volume": "Volume II: Nature's Breath"
  },
  {
    "id": 10,
    "title": "Beauty in Nothing",
    "author": "dhanavan",
    "preview": "Beauty in Nothing\u2014I\u2019m nothing, talking to you,I'm ...",
    "content": "Beauty in Nothing\u2014I\u2019m nothing, talking to you,I'm nothing.Find me in your peace and solace.\nRooms filled with echoes of voices,Yet I am filled with emptiness.But emptiness isn\u2019t a sin\u2014It\u2019s seeking yourself, your soul, in peace.\nZero thoughts, zero emotions,A blank page, left behind,Chose to leave it unwritten.\nNo conclusions, no endings\u2014Well, nothing has nothing to say.Surrender. Free your soul.You will findBeauty in nothing.",
    "emotion": "passion",
    "depth": 0.48,
    "theme": "Uncategorized",
    "volume": "Volume III: The Human Experience"
  },
  {
    "id": 11,
    "title": "Being Single",
    "author": "dhanavan",
    "preview": "Being Single In the world of pairs, I walk alone,...",
    "content": "Being Single\nIn the world of pairs, I walk alone,\nCraving my path, a journey unknown,\nThe freedom whispers in the morning light,\nAn open road, no end in sight;\n\nI dance to the rhythm of my own beat,\nEach day a canvas, my heart skips a seat,\nExploring new places, chasing the sun,\nIn solitude's embrace, I've just begin;\n\nA book on my lap, a cup of warm tea,\nQuiet reflections, just me being me,\nNo need to share my thoughts or dream,\nIn the silence, I found my own theme;\n\nI'm on my own comfort of solitude,\nNo pressure to fit in the scripted role,\nJust me and my passions, my spirit, my soul;\n\nThe world is my oyster, my heart, an open sea,\nEach wave is remainder, I'm perfectly free,\nBeing single is not a void to fill,\nBut a celebration of love in your own will;\n\nTo the stories of freedom, waiting to be told,\nIn the chapter of life, I found my own song,\nIn the heart of my solitude, I truly belong.",
    "emotion": "passion",
    "depth": 0.59,
    "theme": "Love & Romance",
    "volume": "Volume I: Echoes of the Heart"
  },
  {
    "id": 12,
    "title": "Better than He Can",
    "author": "dhanavan",
    "preview": "Better than He Can I won\u2019t lie to you,...",
    "content": "Better than He Can\nI won\u2019t lie to you,\nhe\u2019s not the one for you;\n\nYou spend your days and nights,\nOn a love that doesn\u2019t feel right.\nWhenever you\u2019re ready to let go,\nLet me know\u2026\n\nI could treat you better,\nBetter than he can,\nAny girl like you deserves a gentlemen.\n\nDon\u2019t waste your time on fleeting sparks,\nWhen you could hold my steady heart.\n\nGive me a sign, let me ease your mind,\nI Promise,\nI won\u2019t let you down,\nI won\u2019t let you walk alone,\nJust take my mind,\nLet me be your home.\n\nI\u2019d stop time for you,\nthe second you\u2019d say \u201cI like you too\u201d.\n\nI\u2019ll give you the love,\nYou been missing,\nYou\u2019re the everything, \nI\u2019ve been wishing.",
    "emotion": "passion",
    "depth": 0.36,
    "theme": "Life & Time",
    "volume": "Volume III: The Human Experience"
  },
  {
    "id": 13,
    "title": "Confess",
    "author": "dhanavan",
    "preview": "Confess We met after decades,...",
    "content": "Confess\nWe met after decades,\nCaught in a busy road's snare,\nI was on my motorbike,\nShe, on her scooter there.\n\nShe still loved me, I could see,\nBut I turned away, for her better, for me,\nAmid the honking, she whispered low,\n\"I lo.. \", but the signal said, \"Go\",\n\nI pushed forward, denying her voice, \nBut then, a crash, no choice-\nI rushed back, heart pounding wild,\nAnd there she lay, fragile, defiled.\n\nHer eyes met mine through a haze,\nCalling me close, in a final gaze.\nWith a fading breath, she whispered through,\n\"I love you... will you love me too?\"\n\nHer soul drifted, leaving me torn,\nAmid cries louder than the city's horn.\nNow, the soul who loved me closed her eyes,\nLeaving me in silence, with unheard cries.",
    "emotion": "passion",
    "depth": 0.9,
    "theme": "Love & Romance",
    "volume": "Volume I: Echoes of the Heart"
  },
  {
    "id": 14,
    "title": "Crying Bones",
    "author": "dhanavan",
    "preview": "Crying Bones As I saw you from afar,...",
    "content": "Crying Bones\nAs I saw you from afar,\nFrom the void of space,\nI shattered into a million pieces\nAll at once.\n\nI saw your teary eyes,\nLike dewdrops falling\nFrom the endless sky.\n\nThe threads of my heart unraveled,\nI stood numb,\nWords stumbling,\nAs I watched you cry.\n\nI wished to wipe your tears,\nGently hold your hands,\nWrap you in my arms,\nAnd shelter you within me,\nTo give you the warmth of love.\n\nLet your oceans calm,\nYour mind find peace,\nAnd your heart rest in a serene embrace.\nLet the waves of sorrow fade,\nDrifting softly into the night,\nWhere only love remains.",
    "emotion": "serenity",
    "depth": 0.83,
    "theme": "Sorrow & Grief",
    "volume": "Volume III: The Human Experience"
  },
  {
    "id": 15,
    "title": "Echo - beyond pain",
    "author": "dhanavan",
    "preview": "Echo \u2013 Beyond pain I saw the sea for the first time...",
    "content": "Echo \u2013 Beyond pain\nI saw the sea for the first time,\nMoonlight fell on its face,\nMaking the ocean beautiful, much more--\nTears, like dews, in my eyes.\n\nA Night with no pain,\nNo struggles, no running,\nPinching myself to believe,\nIt wasn\u2019t a dream.\n\nThe hand from nowhere,\nBrought peace and joy to my life.\nEach time ocean waves touches the shore,\nThe tides of my past and pain fades away.\n\nThe hand from nowhere,\nShows me light, a path to life--\nA blessing from the universe,\nI wish to hold it,\nUntil the end.",
    "emotion": "melancholy",
    "depth": 0.62,
    "theme": "Life & Time",
    "volume": "Volume III: The Human Experience"
  },
  {
    "id": 16,
    "title": "Echo - the pain",
    "author": "dhanavan",
    "preview": "Echo \u2013 The pain I\u2019m a girl,...",
    "content": "Echo \u2013 The pain\nI\u2019m a girl,\nBorn somewhere, Grew up somewhere,\nParents separated; I stayed with my mother\u2014\nUntil the echo of change,\n\nI step out, alone,\nA student by day, worker by night,\nHaunted by voices in my head,\nEchoes that kill me each night.\n\nAbused by strangers,\nRunning, hiding, bruised by echoes\nOf pain and silence.\n\nThen, a hand reaches out,\nGentle, understanding\u2014\nI\u2019m afraid, but slowly,\nIt shows me a world beyond pain,\nWhere echoes fade, and hope remains.",
    "emotion": "melancholy",
    "depth": 0.72,
    "theme": "Sorrow & Grief",
    "volume": "Volume III: The Human Experience"
  },
  {
    "id": 17,
    "title": "End of the Day",
    "author": "dhanavan",
    "preview": "End of the Day At the end of the day,...",
    "content": "End of the Day\nAt the end of the day,\nEverything makes sense.\nAt the end of the day,\nEverything feels heavy.\n\nAt the end of the day,\nYou may laugh,\nYou may cry,\nYou may feel numb,\nYou may hate yourself.\n\nAt the end of the day,\nYou may love yourself to the core.\nThings may fall into place,\nOr spiral out of control.\n\nAt the end of the day,\nThe choices you've made\nMay leave you surrounded,\nOr all alone.\n\nAt the end of the day,\nWhat truly matters\nIs what you feel inside.\n\nAt the end of the day.",
    "emotion": "melancholy",
    "depth": 0.29,
    "theme": "Life & Time",
    "volume": "Volume III: The Human Experience"
  },
  {
    "id": 18,
    "title": "Eternal Love",
    "author": "dhanavan",
    "preview": "Eternal Love My love for you is like endless sea, ...",
    "content": "Eternal Love\nMy love for you is like endless sea, \nvast space that no one can explore;\n\nNo thoughts can surpass yours,\nIn my mind;\nBelieving that you\u2019re meant to \nbe mine;\n\nMy love for you is like sunflowers,\nwaiting for the sun to arise;\nAnd gaze with the sunlight,\nEach time, my head arises like that flower\nTo see your presence.\n\nMy love for you is like the nostalgic childhood days, \nI crave for them each and every night,\nI\u2019m drawn to you, craving your presence,\nAs you appear like a Mother,\nguiding her son back from kinder garden.\n\nMy love for you is like child\u2019s first toy,\nI weep day and night, to get you back; \nMy love for you is like loyalty of the dog,\nThat guards his master, in any situations;\n\nMy love for you is like the cold breeze,\nThat carries wishes for rain,\n\nI can\u2019t stop loving you;\nEven when you are afar,\nMy love for you is like dead man\u2019s soul,\nSeeking for the heaven to reach for;\nAs I heard, heaven is the place,\nwhere we can find eternal peace,\nAnd you are my eternal;\nMy Eternal Love.",
    "emotion": "passion",
    "depth": 0.77,
    "theme": "Love & Romance",
    "volume": "Volume I: Echoes of the Heart"
  },
  {
    "id": 19,
    "title": "Farewell",
    "author": "dhanavan",
    "preview": "Farewell Years pass, and the day arrives,...",
    "content": "Farewell\nYears pass, and the day arrives,\nThe last moment,\nThe last time-\nThe day of goodbyes.\n\nI\u2019m so afraid of this,\nYet here it comes.\nI saw her there,\nLingering with her friends,\nSharing her last moments,\nLaughing, talking with them.\n\nMy hands tremble,\nMy palm sweat faster than my heartbeat.\nTwo strings attached,\nYes, my heart aches,\nIt strings tearing.\n\nLike dew on leaves,\nMy eyes begin to fill,\nShe turns, and smiles,\nOur eyes meet and hold-\nShe waves her farewell.\n\nShe\u2019ll never know how badly, how madly,\nI\u2019ll miss her, I wish I could stop time,\nHold her close,\nCry on her shoulder.\n\nBut farewell doesn\u2019t end here,\nA Wish to the universe,\nTo meet her again.",
    "emotion": "melancholy",
    "depth": 0.37,
    "theme": "Life & Time",
    "volume": "Volume III: The Human Experience"
  },
  {
    "id": 20,
    "title": "Girl in my dreams",
    "author": "dhanavan",
    "preview": "Girl in my dreams I met a girl,...",
    "content": "Girl in my dreams\nI met a girl,\nOne who\u2019d lost her love,\nNo parents,\nWorking tirelessly, day and night, just to survive.\n\nI shared with her my sorrow,\nMy life, my love,\nAnd suddenly, she embraced me,\nWrapped me in her gentle affection.\n\nShe made me believe:\nLove will come,\nIf you\u2019ve given your heart freely, it will return to you,\nMore deeply than ever before.\n\nYou\u2019re meant to love and be loved,\nSo keep being yourself; let life unfold.\nLove will find you, no matter how far you wander.\n\nI never knew her name,\nNever took her number,\nBarely recall her face.\nAfter that, she vanished,\n\nThe girl I met in my dreams.",
    "emotion": "passion",
    "depth": 0.91,
    "theme": "Love & Romance",
    "volume": "Volume I: Echoes of the Heart"
  },
  {
    "id": 21,
    "title": "Golden Hour",
    "author": "dhanavan",
    "preview": "Golden Hour As you crossed the view, ...",
    "content": "Golden Hour\nAs you crossed the view, \nI glimpsed a world of you and I,\nUncertain if dream or truth had called;\nBut there you are,\n\nI thought to speak, to bridge the silent space,\nYet you, with quiet and courage, spoke first;\n\nFor months, we lingered in little things,\nThe soft edges of likes and quiet envies,\nEach glimpse a brushstroke in my mind's embrace;\n\nYour blush, shy and swift, played hide and seek,\nLike children lost in some tender game;\n\nAnd then, Silence;\n\nNo words, only the distant ache of strangers eyes,\nMissing the hours spent, each moment a glided memory;\n\nThose were the hours I held Close; \nMy Golden Hour.",
    "emotion": "serenity",
    "depth": 0.53,
    "theme": "Life & Time",
    "volume": "Volume III: The Human Experience"
  },
  {
    "id": 22,
    "title": "Goodbye and Goodbye",
    "author": "dhanavan",
    "preview": "Goodbye and Goodbye Denial\u2014...",
    "content": "Goodbye and Goodbye\nDenial\u2014\nEmpty room where time stood still,\nI craved your smile on every frame.\nSpoke your name like song or mantra\u2014\nAs if pretending could prove me wrong.\nAnger\u2014\nRage lit up the empty space,\nEverything around me sounded loud\u2014\nThe sky, the earth, the voices.\nI cursed your fate for leaving me\nTo bear the weight.\nAll this anger was once love.\nBargaining\u2014\nI starred at the night sky,\nWhispered to the midnight-bright stars\n\u201cJust bring them back, undo these scars\u201d\nWished upon the universe\u2014\nFor it to bend,\nFor chance to mend.\nDepression\u2014\nSilence all around the walls\nHeaviness stole my rest. \nAlready dead, keeping myself alive,\nTo decorate the coffin\nWith love and lies.\nAcceptance\u2014\nYet slowly, light began to spill,\nThrough cracks, I once had meant to fill.\nI speak your name with gentle grace\u2014\nLove lingers, though I miss your face\u2026\nThe last words for you:\nGoodbye, and \nGoodbye.",
    "emotion": "melancholy",
    "depth": 0.57,
    "theme": "Nature & Beauty",
    "volume": "Volume II: Nature's Breath"
  },
  {
    "id": 23,
    "title": "Held Without Hurt",
    "author": "dhanavan",
    "preview": "Held Without Hurt At the spark of something,...",
    "content": "Held Without Hurt\nAt the spark of something,\nYou\u2019ve been showing me.\nA feeling I\u2019ve never known in my entire life.\nNo wonder\u2014\nWhy are you doing this to me?\nWhy me, when you could find someone better?\nI\u2019ve been pushing you away,\nYet you keep showing up.\nAgain and again.\nWhy?\nWhat do you see in me?\nWhat in me caught your eyes?\nI like the way you say my name.\nThere\u2019s so much I want to share\u2014\nBut maybe it\u2019s better kept quiet.\nStill, I\u2019m grateful.\nYou\u2019re the one holding me,\nWithout ever hurting me.\n\nYou\u2019ve become the thought I can\u2019t ignore\u2014\nA comfort I never knew I was craving.\nI\u2019ve built walls no one was meant to climb,\nBut you\u2019re not breaking them\u2026\nYou\u2019re just standing there, patient.\nAnd maybe that means something.\nIt scares me\u2014\nBecause this doesn\u2019t feel like a game.\nIt feels like someone might actually stay.\nAnd maybe, for the first time,\nI don\u2019t want to run.\n\nIf your heart speak honesty,\nAnd your touch holds no harm\u2026\nThen maybe\u2014\nI\u2019ll let you:\nTouch me, \nHold me, \nKiss me\u2014\nLike you see all of me.",
    "emotion": "passion",
    "depth": 0.31,
    "theme": "Love & Romance",
    "volume": "Volume I: Echoes of the Heart"
  },
  {
    "id": 24,
    "title": "Hello... Yellow",
    "author": "dhanavan",
    "preview": "Hello\u2026 Yellow! Yellow!...",
    "content": "Hello\u2026 Yellow!\nYellow!\nSoft light shines on the shore,\nA quiet touch of morning's glow.\n\nYellow!\nSunflowers bloom and dance,\nSwaying in the warm sunlight.\n\nYellow!\nGolden colors fill the sky,\nA place where dreams fly high.\n\nYellow!\nBirds sing in their little nests,\nA song of love and rest.\n\nYellow!\nThe morning light on flowing streams,\nSparkling bright like golden beams.\n\nYellow!\nA color full of life and love,\nBringing warmth from up above.\n\nIt's all Yellow!\nThe way you shine on me\u2014\nYellow!\nYour eyes light up my world,\nYellow!\nMy skin and bones glow softly\u2014\nYellow!\n\nEverything around me is now\u2014\nYellow...",
    "emotion": "hope",
    "depth": 1,
    "theme": "Hope & Inspiration",
    "volume": "Volume III: The Human Experience"
  },
  {
    "id": 25,
    "title": "Her Eyes",
    "author": "dhanavan",
    "preview": "Her Eyes Her eyes are like the sun, lighting up my ...",
    "content": "Her Eyes\nHer eyes are like the sun, lighting up my world,\nHer eyes are like the moon, guiding me through the dark.\nHer eyes are like a void, pulling me in, like the depths of a black-hole.\nHer pupils are like tulips, glowing in vibrant hues,\n\nHer eyes are a garden of flowers, where butterflies chase her beauty.\nHer eyes are heaven, where my soul finds rest.\nIf her eyes were hell, I'd gladly fall at first glance.\n\nWhen I look into them, my heart skips a beat;\nEven my heart forgets how to function.\nMy mind grows cloudy and foggy,\nWhen you gaze at me.\n\nHer eyes are like oceans, calling me to explore their depths,\nHer eyes are magic, leaving me in awe.\nHer eyes are like a ballerina, each movement an art.\n\nHer eyes are a warm place to hide during winter\u2019s cold.\nHer eyes are like Picasso, when art becomes the theme,\nHer eyes are my favorite song, one only I can hear.\n\nThe most beautiful creation, crafted by the divine,\nAre her eyes and I wish for them to be mine.\nShe and,\nHer eyes.",
    "emotion": "passion",
    "depth": 0.31,
    "theme": "Nature & Beauty",
    "volume": "Volume II: Nature's Breath"
  },
  {
    "id": 26,
    "title": "How It Begins",
    "author": "dhanavan",
    "preview": "How It Begins I hid my feelings for him,...",
    "content": "How It Begins\nI hid my feelings for him,\nAs if they were never there,\nWe lingered for months,\nA silent dance, waiting, unsure.\n\nThen, one day, I changed,\nPulled back, stopped talking,\nI don\u2019t know he\u2019d worry,\nDidn\u2019t know he\u2019d care.\n\nBut months passed, and he called,\nSoftly confessing his concern,\nI brushed it off it as nothing,\nEven as he loved me from afar,\nQuietly, patiently, with a love so pure.\n\nIn silence, he stood in shadows,\nHis gaze, tender and true,\nWaiting for a glimpse, a moment,\nAn unspoken bond between us.\n\nThen one day, I couldn\u2019t hold back,\nYears of hidden feelings spilled with tears,\nI searched for him, found him,\nAnd stood before him, nervous, shy.\n\nHe looked at me with patient love,\nAnd I gazed into his ocean eyes.\nFinally, I whispered \u201cI love you too\u201d\nAnd so, our journey of love began.",
    "emotion": "passion",
    "depth": 0.5,
    "theme": "Love & Romance",
    "volume": "Volume I: Echoes of the Heart"
  },
  {
    "id": 27,
    "title": "I Imagine",
    "author": "dhanavan",
    "preview": "I Imagine I imagine us on a bicycle ride,...",
    "content": "I Imagine\nI imagine us on a bicycle ride,\nAnd fly you to the moon,\nSitting there, side by side,\nTo awe the galaxies and your beauty, bright.\n\nI imagine we fell in love with clouds,\nDrifting down, making snow balls,\nPlayfully tossing them all around,\nCrafting snowman, as you are my snow queen.\n\nI imagine we belong to Eden\u2019s garden,\nDancing and tending to love\u2019s pure art,\nWith creatures near and flowers in place,\nResting in Eden, heart to heart.\n\nI imagine us nap under the moonlit skies,\nPicture us, and you with the waves,\nStars in the sky, awe on us,\nI see oceans colours on your face.\n\nForgive me\u2026I imagine a lot,\nI can\u2019t help dreaming of us, as much.",
    "emotion": "passion",
    "depth": 0.49,
    "theme": "Nature & Beauty",
    "volume": "Volume II: Nature's Breath"
  },
  {
    "id": 28,
    "title": "I know what love isn't now",
    "author": "dhanavan",
    "preview": "I know what love isn\u2019t now It isn\u2019t being someone\u2019s...",
    "content": "I know what love isn\u2019t now\nIt isn\u2019t being someone\u2019s second thought.It isn\u2019t begging for attention.It isn\u2019t waiting for a message that never comes,or holding space for someone who only shows up when it's convenient.\nLove isn\u2019t a game where one person playsand the other bleeds.\nSo thank you\u2014for the confusion,the silence,the broken promises,and the sharp goodbye.\nYou didn\u2019t give me the love I needed,but you gave me the lesson I lacked.\nAnd now,I know what I\u2019ll never accept again.\nYou didn\u2019t break me.You revealed me.You showed me how much I was willing to give\u2014and how little you were ready to return.\nBut someone out there,someday,will see all this love and say,\u201cFinally.\u201d\nUntil then,I\u2019ll keep loving myselfin the way you never could.",
    "emotion": "passion",
    "depth": 0.49,
    "theme": "Love & Romance",
    "volume": "Volume I: Echoes of the Heart"
  },
  {
    "id": 29,
    "title": "I Never Wish for",
    "author": "dhanavan",
    "preview": "I Never Wish for I never wished for beauty,...",
    "content": "I Never Wish for\nI never wished for beauty,\nNor for innocence,\nNot for kindness,\nNor a calm presence.\n\nI never wished for care,\nOr intellect deep,\nI never wished for support,\nOr a voice to keep.\n\nI never wished for laughter,\nOr a heart so true,\nI never wished for anything else,\nBut then came you.\n\nYou became everything,\nEverything I never knew,\nThat I was wishing for,\nWhen I found you.",
    "emotion": "passion",
    "depth": 0.21,
    "theme": "Love & Romance",
    "volume": "Volume I: Echoes of the Heart"
  },
  {
    "id": 30,
    "title": "I'm Not Him",
    "author": "dhanavan",
    "preview": "I\u2019m Not Him Don't search for somebody in me,...",
    "content": "I\u2019m Not Him\nDon't search for somebody in me,\nyou won't find the person,\nDon't search for the same mistake,\nMade my somebody, in me,\n\nI am not the echo of your past,\nNor the shadow of love that couldn\u2019t last.\nWhat was lost in another\u2019s game,\nIs not the weight that I should claim.\n\nEach heart bears its own design,\nA canvas fresh, no need to confine.\nSo let me be who I am today,\nNot a reflection of yesterday\u2019s gray.",
    "emotion": "passion",
    "depth": 0.37,
    "theme": "Love & Romance",
    "volume": "Volume I: Echoes of the Heart"
  },
  {
    "id": 31,
    "title": "In Another Universe",
    "author": "dhanavan",
    "preview": "In Another Universe If fate was written in the star...",
    "content": "In Another Universe\nIf fate was written in the stars,\nWhy did we meet, our hearts entwined?\nWhy dream of futures we can\u2019t claim,\nAnd why are we not meant to be one?\n\nLetting go is never easy,\nI can\u2019t be your muse, \nNor pass that closed door,\nI can\u2019t scale these walls,\nOr mountains high,\nYet something in me long to try.\n\nNo money can buy me time machine,\nTo reach you,\nCan\u2019t replace you with,\nMillion rings,\nIf fate\u2019s intent is to pull you away,\nThen why does destiny feel this way?\n\nWhy don\u2019t we rewrite the stars?\nPush back against what they say we are?\nTake my hand, believe in me,\nTogether, against the world, we\u2019ll be free.\n\nImpossible that we can\u2019t be,\nWhen Together feels so right,\nTo get her becomes far more than hard. \n\nAnd if not here,\nThen another time,\nIn another world,\nIn another life,\nIn another universe.",
    "emotion": "nostalgia",
    "depth": 0.48,
    "theme": "Life & Time",
    "volume": "Volume III: The Human Experience"
  },
  {
    "id": 32,
    "title": "In every Moment, You",
    "author": "dhanavan",
    "preview": "In every Moment, You When I close my eyes,...",
    "content": "In every Moment, You\nWhen I close my eyes,\nI see you\nWhen I open my eyes, \nI long to see you\nYour absence,\nMy heart aches\nYour presence,\nMy heart craves\nEvery second, every minute,\nEvery time I want you to be by my side.",
    "emotion": "passion",
    "depth": 0.65,
    "theme": "Love & Romance",
    "volume": "Volume I: Echoes of the Heart"
  },
  {
    "id": 33,
    "title": "Intentions",
    "author": "dhanavan",
    "preview": "Intentions My intentions with you are steady and tr...",
    "content": "Intentions\nMy intentions with you are steady and true,\nTo stand by your side in all you go through.\nIn your highs, I\u2019ll be there, to marvel and cheer,\nIn your lows, I\u2019ll support, to ease every fear.\n\nThough doubts may arise, and shadows might fall,\nI'll choose you, still, through it all.\nLeaving\u2019s not written in the stars for us two,\nI\u2019ll stay, hand in hand, always close to you.\n\nFor love is but part of the path we create,\nBut my deepest wish, my unyielding fate\nIs to build a shared passion, strong and refined,\nWith you, my heart, and our dreams aligned.",
    "emotion": "mystery",
    "depth": 0.57,
    "theme": "Love & Romance",
    "volume": "Volume I: Echoes of the Heart"
  },
  {
    "id": 34,
    "title": "Intezaar",
    "author": "dhanavan",
    "preview": "Intezaar \"Intezaar\" \u2013The most beautiful wordI've ev...",
    "content": "Intezaar\n\"Intezaar\" \u2013The most beautiful wordI've ever heard.\nWaiting for something,A delicate, heart full thing.\nA farmer waits for the skyTo pour down rain, For a small seedTo grow into a beautiful tree, For a bud to blossomInto a glorious, colourful flower.\nA father waits for his childTo enter this world,Like decades passing,As if waiting for a shrubTo bloom upon distant hills,Or for another leap year to arrive.\nAs if waiting for a solar eclipse,Or a child watching the clock,Hoping for their parent\u2019s returnFrom a long day at school.Hoping for someone, somewhere,To return home safe,With miracles yet to unfoldIn their own life.\nEven gods wait for their goddesses \u2013As Radha waits for Krishna,As Sita waits for Rama,As Urmila waits for Laxman.\nWaiting for loved ones,Waiting for a heart to turn,To accept the love offered.\n\"Intezaar\" \u2013Not everyone can wait for you,But if you find one who does,Don\u2019t let them go.",
    "emotion": "passion",
    "depth": 0.4,
    "theme": "Love & Romance",
    "volume": "Volume I: Echoes of the Heart"
  },
  {
    "id": 35,
    "title": "Is this a Poem",
    "author": "dhanavan",
    "preview": "Is this a Poem? If you are heaven, I would love to ...",
    "content": "Is this a Poem?\nIf you are heaven, I would love to die,\nIf you are tears, I would love to cry,\nIf you are pain, I would love to get hurt,\nyou think I'm gonna leave you. but darling your name is my favourite word,\nIf you are the ocean, I'll be the wave,\nIn winter, you are the warmth I crave,\nIf you are the moon, I'll be the closest star,\nI'll always love you, no matter where you are.",
    "emotion": "passion",
    "depth": 0.91,
    "theme": "Love & Romance",
    "volume": "Volume I: Echoes of the Heart"
  },
  {
    "id": 36,
    "title": "Isn't it enough",
    "author": "dhanavan",
    "preview": "Isn\u2019t it enough I have crossing miles for you\u2014...",
    "content": "Isn\u2019t it enough\n\nI have crossing miles for you\u2014\nDidn\u2019t you see the way I long for you?\nA touch of longevity from you,\n\nThis heart, once yours,\nCan hold the pain,\nBut can never love again\u2014\nThat is the only gift I have left to offer.\n\nDidn\u2019t you see my wounds?\nBleeding for you,\nMarked by the scars you give.\n\nDon\u2019t take it for granted\u2014\nThis Love, this soul I surrendered,\nWas meant to bring peace and harmony.\n\nWhy can\u2019t you see?\nThe love, the care I held for you.\nAn admirer, always watching\u2014\nLike gazing at the moon in a lonely night sky.\n\nWondering, what went wrong?\nMe? You? Us?\nWas I not enough?\nWas love not enough?\nWas it ever enough?\nIsn\u2019t it enough?",
    "emotion": "passion",
    "depth": 0.83,
    "theme": "Love & Romance",
    "volume": "Volume I: Echoes of the Heart"
  },
  {
    "id": 37,
    "title": "July",
    "author": "dhanavan",
    "preview": "July Like a water lily, you bloomIn the warmth of J...",
    "content": "July\nLike a water lily, you bloomIn the warmth of June.Like the monsoon, you scatter droplets,Filling the air with life.\nYour absence\u2014Like a toddler waving goodbye,A fleeting moment, yet heavy with longing.Your presence\u2014Like peace after the storm,And yet\u2014I crave the storm and thunder once more.\nLike the dance of summer and monsoon,You shine and rain within me,Revealing the true colours of my soul,Unveiling its quiet beauty.\nLike a traveller on a long road,I wandered\u2014Until you held me with care.\nTwo seasons merging into one:Summer\u2014The beginning and the end.Monsoon\u2014The end and the beginning.",
    "emotion": "passion",
    "depth": 0.33,
    "theme": "Life & Time",
    "volume": "Volume III: The Human Experience"
  },
  {
    "id": 38,
    "title": "Kerosene and Love",
    "author": "dhanavan",
    "preview": "Kerosene and Love A strange glance cast over me\u2014...",
    "content": "Kerosene and Love\nA strange glance cast over me\u2014\nFrom afar,\nShe wanted me to saw her back.\nFor a moment, instead\nI fell into\nA glimpse of you and I.\nIntended to care, love, linger, but\u2014\nAll she want was\u2014a look, a moment\u2019s attention.\nCare,\nTaken for granted.\nLove,\nSeen as baggage of burden, unwanted for the moment.\nAll I showed was pure, No libido,\nBut she craved more and more,\nLike how it ended\u2014\nI was burning down in the fire\nKerosene all over me,\nShe stood in front of me,\nShe asked,\n\u201cWhy won\u2019t you see me?\u201d\nMy skin burned,\nAching to my heart,\nBones turning black.\nMe, and my love for you,\nBurned all away.\nStill, you only craved attention,\nPeak attention.\nYou lunatic.\nWhat kind of animal are you?",
    "emotion": "passion",
    "depth": 1,
    "theme": "Love & Romance",
    "volume": "Volume I: Echoes of the Heart"
  },
  {
    "id": 39,
    "title": "Last Seven Minutes",
    "author": "dhanavan",
    "preview": "Last Seven Minutes As I came into this world, I\u2019ve ...",
    "content": "Last Seven Minutes\nAs I came into this world, I\u2019ve lived a lifetime of hours,\nYet when I leave, I\u2019ll have only seven minutes to see it all.\n\nIn those seven minutes, my life will flash before me,\nA glimpse of every moment since the day I was born:\nMy first words, my first steps, my first kiss, my first victory,\nMy first friend, my first foe, my first love, my first heartbreak.\nThe birth of my child, my first paycheck, my first ride,\nMy first home, my grandchild\u2019s laughter, my \u201cfirsts,\u201d one by one.\n\nIn just seven minutes, I\u2019ll see who I was.\n\nAnd all I want is for, you to be my seven minutes:\nThe moment I met you, the moment I gazed at you,\nThe moment we laughed, the moment we cried,\nThe moment I promised, the moment I held your hand,\nThe moment we embraced, the moment I missed you,\nThe moment we became family.\n\nAll I want are these moments with you,\nTo fill my last seven minutes of life,\nTo carry me from the first moment to the final breath.",
    "emotion": "passion",
    "depth": 0.24,
    "theme": "Life & Time",
    "volume": "Volume III: The Human Experience"
  },
  {
    "id": 40,
    "title": "Little Things",
    "author": "dhanavan",
    "preview": "Little Things I broke a joke,...",
    "content": "Little Things\nI broke a joke,\nBefore she smiles, her lips fold tight,\nBut when she laughs, my heart takes flight.\n\nHer cute little grin,\nLost in the worlds of mine,\nA moment so sweet, feels so divine.\n\nHer irritated face,\nMakes a million thoughts in my mind,\n\u201cHave I done something?\u201d I search to find.\n\nWhile she reads, I walk away, \nHer head held down, lost in the day.\nBut then she looks up, with that intimate gaze,\nIn those little moments, my heart stays.\n\nAs she plays with her hair,\nHeart-shaped curls, makes me blush,\nThe text message you send,\nBrings me smile, a silent hush.\n\nI wish, it could never end,\nIn the little things, my heart will always mend.",
    "emotion": "passion",
    "depth": 0.49,
    "theme": "Love & Romance",
    "volume": "Volume I: Echoes of the Heart"
  },
  {
    "id": 41,
    "title": "Love Again",
    "author": "dhanavan",
    "preview": "Love Again Don\u2019t drift away from me,...",
    "content": "Love Again\nDon\u2019t drift away from me,\nLike magnets forced apart\nStay close,\nLike opposites drawn together.\n\nDon\u2019t hold back your feelings,\nLet them flow without fear.\nDon\u2019t overthink whether to give your heart-\nThe past won\u2019t repeat.\n\nUntil you heal, you\u2019re bleeding on me,\nAnd it\u2019s hard to watch you hurt.\nI\u2019m here, right next to you.\nThrough it all.\n\nJust give me your heart and soul,\nI\u2019ll cherish and nurture them with love and Care.\nLife won\u2019t be the same, \nLet\u2019s restart with new adventures and Awe-\nTo hold again,\nTo care again,\nTo Trust again,\nTo Love again.",
    "emotion": "nostalgia",
    "depth": 1,
    "theme": "Love & Romance",
    "volume": "Volume I: Echoes of the Heart"
  },
  {
    "id": 42,
    "title": "Love of a Woman",
    "author": "dhanavan",
    "preview": "Love of a Woman Your face became the one,...",
    "content": "Love of a Woman\nYour face became the one,\nShe longed to see each morning,\nShe wished to spend her days with you,\nTo wander with you,\nTo ride by your side,\nTo hold you close, so tightly,\nNurture you each and every single day.\n\nIn your highs,\nShe appreciate you for what you are,\nIn your lows,\nShe pulls you close, quiet and calm,\nHush you with her affection,\nWondering what\u2019s running on your mind,\nThough she never asks aloud,\nHold your arms, tight and gentle,\nLet\u2019s your head rest on her shoulder,\n\nShe surprise you with little joys,\nSparks playful fights,\nEven bigger ones, sometimes.\nHer closeness tells you,\nHow deeply she\u2019s into you,\n\nNot every girl would do this,\nBut a woman;\nShe\u2019ll go the distance,\nFor you.\n\nShe\u2019ll communicate with you,\nIn any circumstance,\nShe\u2019ll listen every word you share,\nShe\u2019ll cuddles you often,\nShe\u2019ll acknowledges you,\nShe\u2019ll trusts you,\nShe\u2019ll compromises for you,\nShe\u2019ll loves you unconditionally,\nShe\u2019ll always there for you,\nShe\u2019ll makes decisions with you.\n\nThis is the love of a woman,\nA love that happen only when,\nA woman truly loves.",
    "emotion": "passion",
    "depth": 0.4,
    "theme": "Love & Romance",
    "volume": "Volume I: Echoes of the Heart"
  },
  {
    "id": 43,
    "title": "Love of Sky and Earth",
    "author": "dhanavan",
    "preview": "Love of Sky and Earth The sky roams free, boundless...",
    "content": "Love of Sky and Earth\nThe sky roams free, boundless and wide,\nLike a man with dreams he cannot hide.\nHe brings the dawn, he stirs the night,\nYet slips away beyond our sight.\n\nThe earth, serene, both strong and warm,\nLike a woman\u2019s heart in every form.\nShe feels his rain, she bears his storm,\nHolding life in quiet, steady norm.\n\nIn shadows cast and light revealed,\nTheir bond endures, though concealed.\nGood in bad, bad in good,\nThey find each other as they should.\n\nThough destined to walk their separate ways,\nThe sky and earth meet in quiet displays.\nLike man and woman, worlds apart;\nForever bound by a single heart.",
    "emotion": "serenity",
    "depth": 0.8,
    "theme": "Love & Romance",
    "volume": "Volume I: Echoes of the Heart"
  },
  {
    "id": 44,
    "title": "Loving Him",
    "author": "dhanavan",
    "preview": "Loving Him I thought I met a boy,...",
    "content": "Loving Him\nI thought I met a boy,\nBut I found a man,\nGenuine, wise,\nHe entered my life,\nThe right soul at the wrong time.\n\nI don\u2019t know how it happened,\nBut he fell for me,\nQuietly, deeply.\nOne day, he spoke of love,\nOf dreams, a lifetime spent together.\nI was afraid to open my heart,\nYet drawn to him, every part.\n\nHis presence, his voice,\nThe little ways he made me stay,\nThe late nights waiting for my safe return,\nThe patience, the care,\nWho loves like that anymore?\n\nIn time, I found my answer,\nReady to say \"I love you\" back.\nBut he's no longer here,\nWaiting now among the stars.\nWith tears filling my eyes,\nI whispered to his grave,\n\"I love you.\"",
    "emotion": "passion",
    "depth": 0.7,
    "theme": "Love & Romance",
    "volume": "Volume I: Echoes of the Heart"
  },
  {
    "id": 45,
    "title": "Loyalty",
    "author": "dhanavan",
    "preview": "Loyalty They say loyalty is...",
    "content": "Loyalty\nThey say loyalty is\nHolding on to something\nThat was never there for you.\n\nHow long have I been on hold \u2014\nFor you?\n\nIf you wonder how long\nI can hold on to something\nThat was never mine,\nThe answer is \u2014 forever.\n\nMy loyalty for you \u2014\nLike a wolf, lost and alone\nIn a dense forest,\nHowling at a silence that never answers.\n\nMy loyalty for you \u2014\nLike a lone penguin\nWandering the cold, iced ocean\nOf frozen memories.\n\nMy loyalty for you \u2014\nLike a swan,\nMy final breath\nBelongs only to you.",
    "emotion": "melancholy",
    "depth": 0.2,
    "theme": "Love & Romance",
    "volume": "Volume I: Echoes of the Heart"
  },
  {
    "id": 46,
    "title": "Maple Leaf - The Season of Autumn",
    "author": "dhanavan",
    "preview": "Maple Leaf \u2013 The season of Autumn Autumn whispers t...",
    "content": "Maple Leaf \u2013 The season of Autumn\nAutumn whispers through the trees,\nLeaves drift down\u2014one by one.\n\nI see a beautiful young lady,\nStanding by the fence of the bridge,\nGazing at the golden sunset.\n\nFallen leaves\u2014\nTouch the earth so timidly.\nHer beauty\u2014\nStrikes my soul so fiercely.\n\nLike a maple leaf,\nShe reveals three sides\u2014\nGenerous, calm, divine.\nHer glance\u2014\nLike a hidden wound,\nBleeds unseen.\n\nI've heard\u2014\nThe maple leaf is a symbol\nOf love and affection.\n\nI reach for her,\nA leaf in my hand,\nAnd with it\u2014\nMy heart.",
    "emotion": "passion",
    "depth": 0.64,
    "theme": "Nature & Beauty",
    "volume": "Volume II: Nature's Breath"
  },
  {
    "id": 47,
    "title": "May",
    "author": "dhanavan",
    "preview": "May The season of spring is May,...",
    "content": "May\nThe season of spring is May,\nWhen beautiful, spectacular flowers\nBloom in grace--\nLike the day you were born.\n\nYour love,\nSo gentle and caring,\nAs pure as a mother\u2019s embrace,\nFor May is her month, too.\n\nLike tulips in many hues,\nYour presence, No clues,\nColors my world anew--\nAs tulips do in May.\n\nAll I wish for is you:\nMay I be yours?\nMay you be mine?\nMay I hold your hand?\nMay I dry your tears?\nMay I speak to you?\nMay I kiss you?\n\nThere are million ways to say \u201cMay,\u201d\nBut I hope to hear you say,\n\u201cMaybe\u201d\n\nThe month of yours,\nIs the favourite month of mine--\nMay!!",
    "emotion": "passion",
    "depth": 0.26,
    "theme": "Nature & Beauty",
    "volume": "Volume II: Nature's Breath"
  },
  {
    "id": 48,
    "title": "Migration",
    "author": "dhanavan",
    "preview": "Migration Birds migrate with the seasons,...",
    "content": "Migration\nBirds migrate with the seasons,\nProtecting themselves and kin,\nFrom the harshness of changing skies.\n\nLike them, I too migrate,\nTo cities for survival,\nTo provide for our family.\n\nWherever I wander,\nMy thoughts circle back to you,\nI stay in countless places,\nBut none are ever home.\nThere are many houses,\nYet, you are my home.\n\nWith love, from afar.",
    "emotion": "passion",
    "depth": 0.24,
    "theme": "Love & Romance",
    "volume": "Volume I: Echoes of the Heart"
  },
  {
    "id": 49,
    "title": "Moon's Silent Cry",
    "author": "dhanavan",
    "preview": "MOON\u2019S SILENT CRY. In the dark of night, the rain b...",
    "content": "MOON\u2019S SILENT CRY.\nIn the dark of night, the rain begins to fall,\nSoft tears of the moon, hidden from all.\nThe bright moon shines, but clouds drift near,\nWrapping her close, so no one sees her tear.\n\nHe holds her gently, his mist a warm shield,\nHiding her sorrow that won\u2019t be revealed.\nTogether they stay, the night passing slow,\nMoon and clouds, letting their quiet tears flow.",
    "emotion": "mystery",
    "depth": 1,
    "theme": "Sorrow & Grief",
    "volume": "Volume III: The Human Experience"
  },
  {
    "id": 50,
    "title": "Mr. Moon's Post Office",
    "author": "dhanavan",
    "preview": "Mr. Moon\u2019s Post Office A little girl sat by candlel...",
    "content": "Mr. Moon\u2019s Post Office\nA little girl sat by candlelight,\nWriting a letter late one night\u2014\nTo someone she missed,\nTo someone above,\nA letter filled with sorrow and love.\nShe raised her head and looked outside,\nThrough pale clouds and skies so wide.\nA full moon glowed, calm and bright,\nBathing her tears in silver light.\n\nHer mother said with a quiet tone,\n\u201cIf you miss your grandma, you\u2019re not alone.\nWrite her a letter, from your room\u2014\nAnd send it to Mr. Moon.\nHe\u2019ll know what to do.\u201d\n\nSo the child wrote with trembling pen,\nAbout picnics, lullabies, and \u201cback then.\u201d\nThen whispered through the window pane,\nHer little prayer, soft like rain\u2014\n\u201cMr. Moon, please send this letter\nTo my beloved Grandma in the stars.\nTell her I miss her more than ever,\nAnd ask her\u2014\nCan she visit in the summer holidays?\u201d\n\nFar away, in the silent deep,\nThe Moon stirred softly from his sleep.\nHe heard the voice, pure and small,\nAnd turned to face the Earth\u2019s sweet call.\nWith a faint smile, he sighed inside,\n\u201cMy cratered chest is filled with tides\u2014\nOf letters forgotten, wishes unsaid,\nWords from the living, tears from the dead.\u201d\n---\n\u201cThey ask me for magic,\nFor love returned,\nFor moments lost,\nFor bridges burned.\nAnd though I\u2019m just a ball of stone,\nSomehow I make them feel less alone.\u201d\nAnd so he cradled her words with care,\nTucked the note in the night\u2019s cool air.\nNot promising miracles, nor replies\u2014\nBut watching her dreams drift into the skies.",
    "emotion": "mystery",
    "depth": 0.69,
    "theme": "Nature & Beauty",
    "volume": "Volume II: Nature's Breath"
  },
  {
    "id": 51,
    "title": "Never Really Over",
    "author": "dhanavan",
    "preview": "Never Really Over Even the sun may lost its bright...",
    "content": "Never Really Over\nEven the sun may lost its bright\nEven the earth may stops rotating\nEven the stars won\u2019t shines\nEven we didn\u2019t see each other \nEven we didn\u2019t talk to each other\nEven we are strayed from each other\nEven we are in our own battles\nEven we are in different life\nEven the world\u2019s gonna end\nEven there is nothing left in this universe\nEven no longer I, \nEven all the odds\u2026\nMy soul follows you, \nUntil the eternity\nWherever you go, wherever you stand,\nWherever\u2026 \nMy love for you\nWill never really gets over.",
    "emotion": "hope",
    "depth": 0.46,
    "theme": "Nature & Beauty",
    "volume": "Volume II: Nature's Breath"
  },
  {
    "id": 52,
    "title": "Neverends",
    "author": "dhanavan",
    "preview": "Neverends My love for you,it never fades,...",
    "content": "Neverends\nMy love for you,it never fades,\nIt whispers soft through light and shade,\nBeyond the bounds of time's own thread,\nThrough every beat, by you i'm led;\n\nYour gaze, a spark that lights my soul,\nIn your embrace, i'm deeply whole,\nAs long as breath within me dwells,\nMy heart for you in silence swells;\n\nUntil the stars no longer glow,\nThis love endures, for you to know.",
    "emotion": "passion",
    "depth": 0.87,
    "theme": "Love & Romance",
    "volume": "Volume I: Echoes of the Heart"
  },
  {
    "id": 53,
    "title": "No Submarines No Divers",
    "author": "dhanavan",
    "preview": "No Submarines, No Divers Rustling mind, fogged out...",
    "content": "No Submarines, No Divers\nRustling mind, fogged out\nI wish I could pack my emotions,\nFold my feelings into a black suitcase\u2014\nToss them into the deepest ocean,\nWhere no one could ever reach.\nNo submarines,\nNo divers.\nNo depth could find that grief.\nStorms and thunders front and back\u2014\nI\u2019m running down an endless highway \nTrying to save myself\u2026 from me.\nNo signboards,\nNo cars,\nJust grey, angry clouds\nTrying to exorcise my soul.\nThey fall from the sky\u2014\nNo planes.\nNo birds.\nJust screaming,\nLouder\u2026\nUntil my voice dies.\nStriking the ground\nAt the speed of despair\u2014\nBang!\nNow I\u2019m levitating in space,\nCrushed by asteroids.\nLooking in the mirror\u2026\nLove.\nA Glitch.\nSore eyes.\nTre-- Trembling hands.\nCold heart.\nScars etched deep into my soul.\nMirrors shattered.\nAnd me\u2026\nShattered too.",
    "emotion": "passion",
    "depth": 0.45,
    "theme": "Love & Romance",
    "volume": "Volume I: Echoes of the Heart"
  },
  {
    "id": 54,
    "title": "Not a Farewell",
    "author": "dhanavan",
    "preview": "Not a Farewell Farewell, they say,...",
    "content": "Not a Farewell\nFarewell, they say,\nBut it's more than just a goodbye.\nTo the friends who stood by,\nWho lent their shoulders when we felt low,\nWho lifted us with words that echoed:\n\u201cYou can do it.\u201d\nA wave of the hand, a tear-filled eye\u2014\nThis isn't the end.\nGoodbyes don't stop here.\nLeaving this place,\nWhere years turned into memories,\nLeaves an emptiness\nThat nothing in the world can fill.\nWhen you recall those days,\nA smile will touch your lips,\nBut your heart will ache with longing.\nThose aren't just old days\u2014\nThey're golden days,\nPriceless and irreplaceable.\nSaying \"I miss you\"\nCannot soothe the ache of separation.\nBut when we meet again,\nOh, how much there will be to say.\nMay that day come soon.",
    "emotion": "melancholy",
    "depth": 0.35,
    "theme": "Life & Time",
    "volume": "Volume III: The Human Experience"
  },
  {
    "id": 55,
    "title": "Ocean Colors",
    "author": "dhanavan",
    "preview": "Ocean Colors Standing down on my two feet,On the we...",
    "content": "Ocean Colors\nStanding down on my two feet,On the wet sand,Orange and blue skies above,Cold breeze, a warm space.\nSparkling waves and blue tides,A fierce battle\u2014waves clash,Like heart and brain.\nI saw myself, standing all alone,For a quiet bit of a moment\u2014No grudges. No judges.\nShore waves touch my feet,Washing away sins and ego.My body turns light\u2014like a cloud,Levitating in a state of emotion.\nNo tears. No jinx.Wishing to be me for some time,Waiting for myself\u2014to reclaim me,To hold me, to choose me.\nThe world can turn its back,Yet I stand again\u2014for myself,For who I am\u2014Not for who they want me to be.\nWondering\u2014Life has meaning,But not for me.I don\u2019t want to be mean\u2014Just meaningful.\nI wish solitude and quiet,Peace over everything,To cuddle me in the void of no person.\nMy heart is now filled,With the beauty of ocean colors.",
    "emotion": "serenity",
    "depth": 0.64,
    "theme": "Nature & Beauty",
    "volume": "Volume II: Nature's Breath"
  },
  {
    "id": 56,
    "title": "Ocean's Sad love",
    "author": "dhanavan",
    "preview": "Ocean\u2019s Sad Love The Ocean loved the Moon,...",
    "content": "Ocean\u2019s Sad Love\nThe Ocean loved the Moon,\nShining high and bright,\nBut the Moon loved a Star,\nFar beyond its sight.\n\nHeartbroken, the Ocean cried,\nAnd waves grew sad and deep,\nIts salty tears filled the sea,\nAs it wept itself to sleep.\n\nSince then, the Ocean\u2019s sad and blue,\nIts waves tell the stories true,\nOf love that reached too far,\nFrom Ocean to Moon, from Moon to Star.",
    "emotion": "mystery",
    "depth": 1,
    "theme": "Nature & Beauty",
    "volume": "Volume II: Nature's Breath"
  },
  {
    "id": 57,
    "title": "On a Christmas Eve",
    "author": "dhanavan",
    "preview": "On a Christmas Eve On a cold Christmas night,...",
    "content": "On a Christmas Eve\nOn a cold Christmas night,\nSnow begins to fall, soft and light.  \nPeople in the cities welcome the snow,\nWith hearts aglow, their warmth they show.\n\nThe cities are covered in snow,\nAll around, peaceful glow,\nNeighbor\u2019s homes are filled with cheer,\nWith colorful lights, stockings, and trees so dear.\n\nOn this December night, \nI saw her,\nStanding beneath the towering tree.\nNever have I seen such beauty, so pure,\nThe tree and she, a sight to see.\n\nBrighter than the lights, surround her,\nShe shines more than star- above.\n\nIn her ice-skates, she glides with grace,\nMoving so gently in her own space. \nSlow and serene, with effortless ease,\nEven ice would melt, before her breeze.\n\nMy December feels like summer\u2019s glow,\nWhen she gazes at me, my heart does grow.\nI wish this night could last a little longer,\nAn Eternal evening, forever stronger.",
    "emotion": "hope",
    "depth": 0.5,
    "theme": "Nature & Beauty",
    "volume": "Volume II: Nature's Breath"
  },
  {
    "id": 58,
    "title": "On a Rainy Day",
    "author": "dhanavan",
    "preview": "On a Rainy Day I wondered, how the...",
    "content": "On a Rainy Day\nI wondered, how the\nDew drops on a flower,\nClung to its petals,\nLingering there so long,\n\nThe sky drizzles;  \nA cold breeze flows,\nShivering me like a child,\nVeins stilled for a moment.\n\nShe toddles slowly,\nHolding a yellow umbrella,\nHer hands rising, gentle,\nTo catch raindrops in her soft palms.\n\nI watched her from afar,\nEntranced by her beauty,\nMore delicate than\nThe dew-lit flower itself.\n\nLowering her umbrella,\nA raindrop kissed her face,\nSplattering hues of colour,\nShe blushed, soft as a kitten\u2019s purr.\n\nMy heart skipped a beat, \nShattering like a raindrop\u2019s splash,\nScattering into a million pieces.\n\nAnd in a blink,\nShe vanishes from sight,\nLeaving a quiet wish to,\nSee her again.",
    "emotion": "serenity",
    "depth": 0.86,
    "theme": "Nature & Beauty",
    "volume": "Volume II: Nature's Breath"
  },
  {
    "id": 59,
    "title": "One Sided Love",
    "author": "dhanavan",
    "preview": "One Sided Love I enjoy my own company,...",
    "content": "One Sided Love\nI enjoy my own company,\nTalking with friends,\nUntil I saw her - a sparkling star,\nUnlike anyone I\u2019d ever seen.\n\nI fell in love, one-sided,\nUnable to confess,\nMy words trembled, \nStuck in my throat.\n\nA random boy talks to her\nI feel possessive, nostalgic,\nWishing I could stand beside her,\nJust for a little conversation.\n\nThen, I compared myself to her,\nRealizing she\u2019s out of my league,\nAccepting, I couldn\u2019t keep her by my side.\n\nSo I chose to let her go,\nYet she left her mark on me.\nThe beauty and pain of one-sided love,\nHave made me a better man.",
    "emotion": "passion",
    "depth": 0.42,
    "theme": "Love & Romance",
    "volume": "Volume I: Echoes of the Heart"
  },
  {
    "id": 60,
    "title": "Passion",
    "author": "dhanavan",
    "preview": "Passion A fire lit up in the heart,...",
    "content": "Passion\nA fire lit up in the heart,\nTo reach the goal like a dart,\nStruggling day and night,\nTo achieve this in sight,\n\nSome days are like magic,\nWorking for us,\nSome days are like tragic,\nWorking against us,\n\nWithout a single penny,\nWe crossed miles after miles,\nSpent hours upon hours,\nWorking hard like ants to be the best,\nWith little rest,\n\nEach one has a dream to become someone,\nAn actor, to entertain,\nA lawyer, to maintain law,\nA doctor, to cure the sick,\nA scientist, to discover,\nAnd more, and more.\n\nThey set the blaze in their veins,\nChasing the goal of their lives,\nEach and every day,\nNo excuses, no regrets,\n\nAn unsettled torch, flames brighter than fire,\nWithout reaching them his soul wouldn't tire,\nA passion that drives his life.",
    "emotion": "passion",
    "depth": 0.66,
    "theme": "Life & Time",
    "volume": "Volume III: The Human Experience"
  },
  {
    "id": 61,
    "title": "Peace",
    "author": "dhanavan",
    "preview": "Peace After the huge battle with me and the world,...",
    "content": "Peace\nAfter the huge battle with me and the world,\nI restlessly scatter here and there\nA battle with me and myself,\nA battle between the brain and heart.\n\nI had nowhere to go, but there is some place called Home,\nTo find something, to unveil something,\nTo endure something, to nurture something,\nTo rescue the child, underneath from the portals of pain\n\nThe Portal to pain, a fallen angel\nBetrayed, Cornered, by the messy world.\nThose Grudges, anger, he held\nEnds up in Tears;\nEnds up in Sufferings;\nEnds up in Solace.\n\nAt the end of every single day;\nIm on my knees, In front of you,\nPlease show me the light to lead my soul.\nShow me the lap to lay my head\nAnd close my eyes for an hour \nTo escape from the painful reality\n\nSo please \nPeace\u2014\nHold me with your magic hands\nSweet peace\u2014\nI left my soul to you\nSo please\nRest the soul in peaceful peace\u2026",
    "emotion": "serenity",
    "depth": 0.46,
    "theme": "Sorrow & Grief",
    "volume": "Volume III: The Human Experience"
  },
  {
    "id": 62,
    "title": "Playful Love",
    "author": "dhanavan",
    "preview": "PLAYFUL LOVE I want to play and laugh with you,...",
    "content": "PLAYFUL LOVE\nI want to play and laugh with you,\nLike a pup with skies so blue,\nChasing butterflies without a care,\nIn garden filled with flowers fair.\n\nA gentle love, so soft and true,\nI just want to be with you.\n\nPup and Butterfly,\nYou and I.",
    "emotion": "passion",
    "depth": 0.63,
    "theme": "Love & Romance",
    "volume": "Volume I: Echoes of the Heart"
  },
  {
    "id": 63,
    "title": "Poet's Wish",
    "author": "dhanavan",
    "preview": "Poet\u2019s WishA wish from the poet, To become a poem,...",
    "content": "Poet\u2019s WishA wish from the poet,\nTo become a poem,\nYet in the still night,\nNo hand to hold the pen tight.\nA longing unspoken,\nIn verses unbroken,\nThe poet becomes words\nThat only silence has heard\nBut no one's there,\nTo write a poem.",
    "emotion": "serenity",
    "depth": 0.33,
    "theme": "Life & Time",
    "volume": "Volume III: The Human Experience"
  },
  {
    "id": 64,
    "title": "Prayers",
    "author": "dhanavan",
    "preview": "Prayers  Since childhood, I learned:...",
    "content": "Prayers \nSince childhood, I learned:\nIf you want something,\nSend a prayer to the one above,\nHe will make it so.\nPrayers are the message,\nA silent bridge between you and the Almighty.\n\nThe hospital walls,\nHave heard so many prayers,\nPleading for loved ones to return to life.\nThe walls in holy places,\nWitnessed endless prayers,\nAsking to ease the sorrows in life.\n\nPeople pray\nEarly in the morning,\nLate at night,\nBefore and after meals,\nTo show gratitude.\n\nI pray for good life,\nFor myself, for others,\nAnd their kins.\n\nMost of all, I pray for you-\nTo keep a smile on your face,\nEvery single day,\nTo turn your sorrows to ashes,\nEven, if you\u2019re not meant for me,\nI still keep you in my prayers.",
    "emotion": "melancholy",
    "depth": 0.23,
    "theme": "Life & Time",
    "volume": "Volume III: The Human Experience"
  },
  {
    "id": 65,
    "title": "Rose and a Stranger",
    "author": "dhanavan",
    "preview": "Rose and a Stranger In the shadows of a dense, dark...",
    "content": "Rose and a Stranger\nIn the shadows of a dense, dark wood,\nA radiant rose in silence stood.\nVelvet petals, crimson bright,\nA lonely glow in fading light.\n\nA stranger wandered through the trees,\nDrawn by beauty on the breeze.\nOne fleeting glance, his heart was claimed,\nBy the rose\u2014untouched, untamed.\n\nHe longed to speak, to take it near,\nTo show the world beyond, so clear.\nDay by day, he softly spoke,\nHoping love in time awoke.\n\nSeasons passed, yet still she swayed,\nRooted firm, in shade she stayed.\nHis hands reached out\u2014her thorns struck deep,\nAnd in his wounds, love learned to weep.\n\nAt last, he knew\u2014she would not leave,\nNo matter how his heart believed.\nSo with a sigh, he stepped away,\nCarrying love that chose to stay.\n\nThrough silent paths, he walked alone,\nWith pain and memories overgrown.\nFor some are meant to bloom apart,\nYet still take root within the heart.",
    "emotion": "passion",
    "depth": 0.58,
    "theme": "Love & Romance",
    "volume": "Volume I: Echoes of the Heart"
  },
  {
    "id": 66,
    "title": "Seasons of Love",
    "author": "dhanavan",
    "preview": "Seasons of Love In Spring,...",
    "content": "Seasons of Love\nIn Spring,\nOur love blooms like Florida's flower,\nwhite petals whispering purity,\nA tender touch that captivates the heart,\nLike butterflies, we wanderlust here and there;\n\nIn Summer,\nLike glaciers melting in the sun,\nOur love flows, transforming into oceans,\nWe melted like butter, enriching the feast of life;\n\nIn Autumn,\nWe fall for each other presence,\nLike leaves cascading from branches,\nOur laughter grows gentle, matured,\nA bond between us, never fades,\n\nIn Winter,\nOur love turns cold, yet cozy,\nWe cuddle tightly against the chilling breeze, \nSeeking warmth from summer's embrace,\nTreasuring the fondness of spring;\n\nThus, these are\nThe Seasons of Love.",
    "emotion": "passion",
    "depth": 1,
    "theme": "Nature & Beauty",
    "volume": "Volume II: Nature's Breath"
  },
  {
    "id": 67,
    "title": "She Dreamed about Me",
    "author": "dhanavan",
    "preview": "She Dreamed about me. She once told me, ...",
    "content": "She Dreamed about me.\nShe once told me, \nShe saw me in her dreams.\nI didn\u2019t ask her about the dream,\nBut I often wish it was about us.\n\nA dream, where she accepts my proposal,\nAnd we became lovers,\nWalked together along the streets,\nHand in hand, strong.\n\nWe share our dreams, \nLaughing until we can\u2019t stop.\nEnjoying good food, \nI feed her, her favourite sweet.\nShe blushes, covering her smile.\n\nWe ride for miles, hands intertwined,\nEmbracing every moment,\nCherishing the little things, \nWhile she talks, I gently moved her hair aside,\nFingers brushing her face.\n\nWe spent precious time together,\nWishing this bond, between us will remain,\nCloser and stronger, like the love we share.",
    "emotion": "mystery",
    "depth": 0.64,
    "theme": "Hope & Inspiration",
    "volume": "Volume III: The Human Experience"
  },
  {
    "id": 68,
    "title": "She-Aval",
    "author": "dhanavan",
    "preview": "She/Aval I didn't meet a girl, I met a Woman...",
    "content": "She/Aval\nI didn't meet a girl, I met a Woman\nHer wisdom shines through every lesson learned,\nWith every challenge faced, she's risen stronger,\nIn her presence, i found my own heart burned;\n\nHer baby blue eyes are a cosmic sea,\nPulling me in, lost in the vast space,\nSinking gently into a timeless dream,\nWhere there's no way back, no familiar place.\n\nShe speaks like a toddler, pure and unguarded,\nHer voice melts me, like glaciers in the sun,\nEach word a whisper, both tender and bold,\nWrapped in kindness, where love has begun.\n\nHer hands are warm, cradling our love,\nHer Fingers paint the sky above,\nA gentle stroke adds color to my world,\n\nHer laughter dances like stars in the night,\nA melody sweet, filling darkness with light.\nWith each touch, she weaves magic and grace,\nCreating a haven, our sacred space.\n\nShe walks like a swan,\nGliding down the aisle,\nWith each gentle step, flowers bloom in her wake,\n\nI long to stay beneath her feet,\nUntil my last breath, for love\u2019s sweet sake.",
    "emotion": "passion",
    "depth": 0.59,
    "theme": "Love & Romance",
    "volume": "Volume I: Echoes of the Heart"
  },
  {
    "id": 69,
    "title": "Shoot for the Second Star",
    "author": "dhanavan",
    "preview": "Shoot for the Second Star Growing up is just a wast...",
    "content": "Shoot for the Second Star\nGrowing up is just a waste of time,\nThe world will hit you, left and right,\nFairy tales? They aren\u2019t the truth,\nPeter pan, he had it right.\n\nThe world is built on faith,\nOn trust, and pixie dust.\nHold tight to happy thoughts,\nAnd you\u2019ll find yourself in flight.\n\nThe first star you aim for,\nMight vanish, fade from sight,\nSo set your course for the second star,\nAnd reach it with all your might.\n\nNot everyone bound for the first star,\nSome are meant for the second light.",
    "emotion": "mystery",
    "depth": 0.63,
    "theme": "Nature & Beauty",
    "volume": "Volume II: Nature's Breath"
  },
  {
    "id": 70,
    "title": "Silent Love",
    "author": "dhanavan",
    "preview": "Silent Love In the silence of stars, our secret was...",
    "content": "Silent Love\nIn the silence of stars, our secret was kept;\nA love waiting, like dawn, in the night gently swept;\nA tale of two hearts; yet untold;\n\nIn the night sky, one lone star burns bright,\nA solitary witness to our love, hidden from sight;\nWaiting patiently, beneath the dark\u2019s veil,\nFor the morning light, our truth to unveil;\n\nA breeze flows through the grass, silent and light,\nWhispering love's secret, hidden from sight.\nIn quiet breaths, it dances unseen,\nTouching each blade, soft and serene.\n\nBirds rest in their nest, nestled close,\nWrapped in a quiet love only nature knows,\nUnder the night\u2019s watch, they settle with ease;\nA tender stillness, cradled by the breeze;\n\nLike them, my heart finds a place to stay,\nIn the promise of dawn, in love\u2019s gentle sway.",
    "emotion": "serenity",
    "depth": 1,
    "theme": "Love & Romance",
    "volume": "Volume I: Echoes of the Heart"
  },
  {
    "id": 71,
    "title": "Sorry",
    "author": "dhanavan",
    "preview": "Sorry I made a mistake,...",
    "content": "Sorry\nI made a mistake,\nIt wasn\u2019t something I meant to do.\nIf my words or actions hurt you,\nPlease know that I never wanted that.\n\nIf I made you feel small,\nOr like you didn\u2019t matter,\nI\u2019m here, asking for forgiveness\u2014\nI\u2019m truly sorry.\n\nEvery night, I feel the weight of this,\nThoughts of you fill my mind,\nReminding me of the pain I caused.\nAnd I\u2019m so sorry.\n\nPlease, forgive my mistake.\nI promise, from the bottom of my heart,\nI won\u2019t let this happen again.\n\nDon\u2019t leave me.\nPlease, come back to me.\nWith tears in my eyes,\nI\u2019m here, asking for your forgiveness.",
    "emotion": "melancholy",
    "depth": 0.42,
    "theme": "Sorrow & Grief",
    "volume": "Volume III: The Human Experience"
  },
  {
    "id": 72,
    "title": "Stay",
    "author": "dhanavan",
    "preview": "Stay O my beloved,I count the days and nights witho...",
    "content": "Stay\nO my beloved,I count the days and nights without you,Your absence leaves an empty space\u2014A void no one else can fill.\nLike seasons, you fade too fast,Like the years, you slip away,Like the moon, you drift farther from me.\nBut now, you stand before me\u2014Stay a little longer.My heart aches for your presence,Stay, just a little longer.\nYour voice is a symphony,A melody I long to hear.Your presence awakens a thousand flowers,Breathing life into my world.\nStay a little longer.Before you leave,Hold me close in your gentle arms,Let your hands linger in mine.\nKiss me once before you go.\nStay\u2014Until the skies turn golden.Stay\u2014Until I can\u2019t let you go.Stay\u2014Until my last breath.Stay\u2014Until the world fades away.",
    "emotion": "nostalgia",
    "depth": 0.77,
    "theme": "Nature & Beauty",
    "volume": "Volume II: Nature's Breath"
  },
  {
    "id": 73,
    "title": "The Eldest Daughter",
    "author": "dhanavan",
    "preview": "The eldest daughter The eldest daughter,...",
    "content": "The eldest daughter\nThe eldest daughter,\nThey tell me to be smart,\nThey tell me to be an example,\nThey tell me to work hard,\nThey tell me to never give up,\nThey tell me, they tell me, they tell me,\n\nThey tell me and I hear,\nThey tell me and I understand,\nThey tell me and I do,\n\nBut in the end,\nThey didn't tell me how to be me.",
    "emotion": "neutral",
    "depth": 0.2,
    "theme": "Uncategorized",
    "volume": "Volume III: The Human Experience"
  },
  {
    "id": 74,
    "title": "The End and the Beginning",
    "author": "dhanavan",
    "preview": "The End and the Beginning They walk through echoes ...",
    "content": "The End and the Beginning\nThey walk through echoes of memories past,\nBuilding bridges that didn't last,\nWith trembling hands, they reach and yearn,\nFor whispered words and lessons learned;\n\nIn every corner, shadows fall,\nThey hear each other's laughter call,\nAn empty bed,a hollow ache,\nMissing piece that heartache makes;\n\nTears flow like rivers, deep and wide,\nFor broken dreams they couldn't hide,\nEach sob a plea, a wish, a cry,\nA hope to mend what said goodbye;\n\nOne gentle dawn, their paths align,\nTwo souls entwined in love's design,\nThey hold each other, wounds now healed,\nIn tender arms,the truth revealed.",
    "emotion": "melancholy",
    "depth": 0.73,
    "theme": "Sorrow & Grief",
    "volume": "Volume III: The Human Experience"
  },
  {
    "id": 75,
    "title": "The Golden Key",
    "author": "dhanavan",
    "preview": "The Golden Key I know you're not ready for love,...",
    "content": "The Golden Key\nI know you're not ready for love,\nBut someday, you will be.\nAnd on that day,\nI'll be here, waiting\u2014\nFor the love meant to be.\n\nYou hold the key,\nThe golden key to my heart,\nThe only one\nWho can unlock\nThe love I keep for you.\n\nUntil then,\nGuard it well,\nThis magical key\u2014\nFor when the time is right,\nIt will lead you back to me.",
    "emotion": "passion",
    "depth": 0.83,
    "theme": "Love & Romance",
    "volume": "Volume I: Echoes of the Heart"
  },
  {
    "id": 76,
    "title": "The Last Table",
    "author": "dhanavan",
    "preview": "The Last Table The last unwritten page\u2014...",
    "content": "The Last Table\n\nThe last unwritten page\u2014\nFrom the diary of love.\nI wonder what went wrong,\nStanding at the airport,\nA ticket trembling in my hand.\n\nLosing the one you love,\nYour admirer, your everything,\nHurts like hell\u2014\nBut it\u2019s just another phase of life,\n\nStill, I cherish the moments\u2014\nThe trips, the travels, and golden sunlight,\nThe starry night skies with folded hands,\nShared smiles and silent sorrows.\n\nDates and dinners\u2014\nSurprises and hugs,\nWhistling in a crowded movie theatre,\nStealing kisses at a birthday party.\n\nI hold on to every single moment,\nEtched in the back of my mind.\nYou are always there\u2014\nNot just in my thoughts,\nBut in my heart.\n\nI nurture the love you gave me\u2014\nThe gifts, this diary,\nThe last dinner we shared.\nTables filled for the midnight party,\nBut one remained in the corner\u2014\nWhere we confessed our love\nAnd our separation.\nThe last Table.",
    "emotion": "passion",
    "depth": 0.58,
    "theme": "Love & Romance",
    "volume": "Volume I: Echoes of the Heart"
  },
  {
    "id": 77,
    "title": "The Love You Can't Deny",
    "author": "dhanavan",
    "preview": "The Love You Can\u2019t Deny Don\u2019t tell me you can\u2019t lov...",
    "content": "The Love You Can\u2019t Deny\nDon\u2019t tell me you can\u2019t love me; I see it in your eyes,\nA quiet whisper your heart denies.\nDon\u2019t tell me to search for someone new,\nWhen every beat says my place is with you.\n\nDon\u2019t tell me to go, don\u2019t turn me away,\nDon\u2019t speak of a world where we drift and stray.\nDon\u2019t say we\u2019re not meant; I can\u2019t let it be,\nWhen the space in my heart is shaped perfectly by we.\n\nSo tell me you\u2019ll love, as your gaze reveals,\nThat I\u2019m more than a chance, I\u2019m the love you feel.\nTell me the chase, for you, ends here,\nThat I\u2019m all you need, that it\u2019s crystal clear.\n\nSay you\u2019ll stay close, for every breath,\nThat our love will outlast time and death.\nAnd as I hand you my pounding heart,\nPromise to keep it, alive, as we are never apart.",
    "emotion": "passion",
    "depth": 0.79,
    "theme": "Love & Romance",
    "volume": "Volume I: Echoes of the Heart"
  },
  {
    "id": 78,
    "title": "The Promise of Patience",
    "author": "dhanavan",
    "preview": "The Promise of Patience I know I was late, But I kn...",
    "content": "The Promise of Patience\nI know I was late, But I know it was worth to wait.\nI know I was late, But I know I'm here to give you everything you deserve to get.\nI know I was late, But I know you've been hurt a lot.\nI know I was late, But I know you weren't treated right.\nI know I was late, But I'm here to Wipe that tears on your face.\nI know I was late, But I'm here to make that Smile on your face.\nI know I was late, But I'm here to Buy your favourite Flower.\nI know I was late, But I'm here to see the eyes that bring me back to life, out of the blue.\nI know I was late, But I'm here to be in your highs and lows, ready to stand by you, no matter what.\nI know I was late, But I'm here to wait for you, ready to embrace every moment we have ahead.\n\nMy hands are open for you, like the Canvas waiting for the paint.\n\nNo matter how long it takes,\nWhenever you are ready,\nI will be here, a steady heart in the storm, To show you that love can heal and transform,\nMend your soul and bring back to life as it was before, like the Child's Lullaby\nWith every moment shared, and every word spoken true,\nKnow that I'm here forever devoted to you,\nSo take your time, let your heart mend and grow,\nFor I will be waiting with love's gentle glow.",
    "emotion": "passion",
    "depth": 0.34,
    "theme": "Life & Time",
    "volume": "Volume III: The Human Experience"
  },
  {
    "id": 79,
    "title": "The Shades",
    "author": "dhanavan",
    "preview": "The Shades Peoples are masking\u2014...",
    "content": "The Shades\nPeoples are masking\u2014\nto hide their inconvenience,\nraw emotions, vulnerabilities.\n\nI gave them a name:\nShades\nAs a normal person,\nI too have shades,\nbut they are different.\n\nI found the art of writing poetry \nthrough the curse of loving someone.\nI can romanticise a moment,\nand just as easily, \nphilosophize the same.\nI can love you to death\u2014\nand walk away\nas if you never existed.\nIn love,\nI\u2019m a haloed angel,\nand a cursed devil.\nTwo shades:\nlight and dark, black and white,\nyin and yang, angel and devil,\nheart and brain, good and evil,\nlove and lust, praise and curse\u2026\n\nI crave to write it out, \nand I\u2019d die to read it back in.\nBut in the end\u2014\nI wear my shades like skin,\nnot to hide,\nbut to remind myself\nthat I am made of many truths,\nand all of them\nare real.",
    "emotion": "passion",
    "depth": 0.4,
    "theme": "Love & Romance",
    "volume": "Volume I: Echoes of the Heart"
  },
  {
    "id": 80,
    "title": "The Things That Still Hold Me",
    "author": "dhanavan",
    "preview": "The Things That Still Hold Me I am not the knife\u2014no...",
    "content": "The Things That Still Hold Me\nI am not the knife\u2014not the rooftop, not the speeding light.I am what\u2019s left\u2014and somehow, that\u2019s still something.\nA cup of coffeestill warm in my trembling hands.A temple\u2019s silence,where divine hears me,even when no one else does.\nClouds drift like thoughts I can\u2019t catch,but they don\u2019t ask anything from me.Mountains stand tall\u2014not unbroken,just unmoved by storms.\nThere\u2019s poetry in me,even when I don\u2019t believe in the poet.Stories in pages I escape into,rides in my bike,where the road forgets my name\u2014and so do I.\nMovies that make me feel again.Books that remind methere are still other lives,and maybe\u2014still\u2014other chances.\nI\u2019m not here because I\u2019m strong.I\u2019m here becausethese small thingswhisperedstay.",
    "emotion": "serenity",
    "depth": 0.53,
    "theme": "Hope & Inspiration",
    "volume": "Volume III: The Human Experience"
  },
  {
    "id": 81,
    "title": "The Train",
    "author": "dhanavan",
    "preview": "The Train  In a crowded train, amid rush and sound,...",
    "content": "The Train \nIn a crowded train, amid rush and sound,\nShe stood there quietly, beauty unbound,\nAn artist, dreaming of colors unseen,\nAnd I, a poet, lost in words between.\n\nWe stood apart, yet our eyes would meet,\nIn the silent gaze, the world felt complete.\nStrangers, yes, bound by thread unseen,\nOur eyes searching for moments between.\n\nNo words spoken, just smiles exchanged,\nAs if each station drew us, unarranged.\nWe watched, we waited, hearts drawn near,\nTwo souls connected, in silence, clear.\n\nWithout realizing, I penned a verse,\nLines of her, both blessing and curse.\nShe, in her own world, sketched my face,\nEach lost in an unspoken embrace.\n\nUnaware of our hidden art,\nYet drawn together, piece by part.\nIn the mirror\u2019s glimpse, my notebook lay,\nShe caught a glance, words in disarray.\n\nI left it there, my heart on the page,\nAnd watched her read, blush on stage.\nThe next day she came, with art in hand,\nA portrait of me- her silent command.",
    "emotion": "passion",
    "depth": 0.27,
    "theme": "Love & Romance",
    "volume": "Volume I: Echoes of the Heart"
  },
  {
    "id": 82,
    "title": "The Wounds",
    "author": "dhanavan",
    "preview": "The Wounds Immense pain\u2014...",
    "content": "The Wounds\nImmense pain\u2014\nCaused by yourself, or someone else.\nImmeasurable, Unbearable.\nWounds are gifts,\nGiven by those we love.\nCut. Sharp. Deeper.\nThey say\u2014\nTime heals everything.\nNever.\nTime only teaches you how to live with it.\nEven wounds are traumatised.\nNumb to pain, even when bleeding.\nYet clingy.\nBandages, dressings\u2014they won\u2019t fix it.\nDon\u2019t touch the wound\nIn the middle of healing.\nLet it be.\nOne touch\u2014nostalgia.\nIt may scare you,\nIt may ache.\nYet,\n Never touch it.\nLeave it as it was.\nIn the end\u2014\nWounds may become scars.\nScars with memories.",
    "emotion": "passion",
    "depth": 0.63,
    "theme": "Life & Time",
    "volume": "Volume III: The Human Experience"
  },
  {
    "id": 83,
    "title": "Thoughts of You",
    "author": "dhanavan",
    "preview": "Thoughts of You As I chilling out in my sole,...",
    "content": "Thoughts of You\nAs I chilling out in my sole,\nThoughts of you came into my mind,\nLike the scent of the spring flowers.\n\nThoughts of you made me smile,\nMade me bliss,\nThoughts of you made my day,\nTender and calm.\n\nThoughts of you made me happy,\nWithout no reason,\nThoughts of you made me love,\nBe kind to others,\n\nThoughts of you made my work,\nUndone to done.\nThoughts of you made me to chase\nMy dreams.\n\nEvery song I heard,\nAll I found is thoughts of you.\nEvery word I read, \nAll I found is thoughts of you,\nEvery lyric defines,\nThoughts of you.\n\nThoughts of you made me,\nA better man,\nThoughts of you murdered,\nThe demon inside me.\nThoughts of you frees,\nThe soul inside me.\nThoughts of you Identifies,\nWho I am.\n\nThoughts of you;\nThoughts of you;\n\nChanged a mess into beauty,\nCage bird into free bird,\nAnger into Calm,\nSin into virtue,\nHell into heaven,\nPain into peace.",
    "emotion": "serenity",
    "depth": 0.27,
    "theme": "Nature & Beauty",
    "volume": "Volume II: Nature's Breath"
  },
  {
    "id": 84,
    "title": "To the Girl Who Taught Me What Love Isn't",
    "author": "dhanavan",
    "preview": "To the Girl Who Taught Me What Love Isn\u2019t You didn\u2019...",
    "content": "To the Girl Who Taught Me What Love Isn\u2019t\nYou didn\u2019t break me.You taught me.Not in the way good teachers do,but in the way a storm teaches a tree\u2014which roots hold,and which ones crumble when the winds howl.\nYou taught me that loveisn\u2019t just words wrapped in pretty excuses.It\u2019s not an occasional text,or a fleeting call when guilt weighs heavy.It isn\u2019t blocking and unblocking,as if affection were something you could earnand lose with a simple click.\nYou taught me that\u201cI don\u2019t want to hurt you\u201ddoesn\u2019t erase the hurt.It isn\u2019t enough to say you won\u2019t break someoneif you\u2019re already cracking them with silence.\nYou made me feel like I was too much to love\u2014but the truth is, I just loved you deeperthan you were ready to be loved.I gave you loyalty without a contract,attention without conditions,a kind of love that had no deadlines.But what did you give back?Confusion. Silence.A thousand \"maybes\" dressed as care.\nAnd still, I stayed.Because I believed in the spark,even when it burned my hands.But no more.",
    "emotion": "passion",
    "depth": 0.62,
    "theme": "Love & Romance",
    "volume": "Volume I: Echoes of the Heart"
  },
  {
    "id": 85,
    "title": "Travel",
    "author": "dhanavan",
    "preview": "Travel After long, hard days,...",
    "content": "Travel\nAfter long, hard days,\nI started my bike, a long ride,\nSomewhere far away from home--\nA tour for my soul.\n\nTo flow with the love and care of nature,\nLike the gypsy clouds that travel the world,\nI saw roads covered with freezing fog,\nIts chill seizing my breath.\n\nI saw the golden sunrise slowly shine on me,\nBright, beautiful and full of grace\u2014\nFolks of birds flew beside me,\nShowing a path to wonders unseen\u2014\n\nCrossing big, elegant, marvellous bridges,\nFeels like crossing dimensions after dimensions,\nThe ocean waves touch the shores, then recede,\nA feather\u2019s touch, easing pain over time.\n\nWalking thru the forest, the soft ambient sounds--\nBirds chirping in branches, insects crawling,\nLeaves dancing in open air,\n\nTowering mountains, a vast blue sky,\nWith clouds drifting over peaks,\nGreen grass swaying in patience and devotion,\nEasing my soul, inviting evolution,\n\nAt last, I returned home,\nA new person of myself.",
    "emotion": "passion",
    "depth": 0.48,
    "theme": "Nature & Beauty",
    "volume": "Volume II: Nature's Breath"
  },
  {
    "id": 86,
    "title": "Two Daughters",
    "author": "dhanavan",
    "preview": "Two Daughters I have dreamed of this day...",
    "content": "Two Daughters\nI have dreamed of this day\nSince the moment I understood life.\nAnd now, I\u2019m living it.\n\nSpeaking of miracles\u2014\nI always wished for a daughter,\nWith eyes that sparkle like the stars,\nTiny fingers wrapped around mine,\nSoft, fluffy little hands,\nAnd small pinkish feet,\nA perfect piece of my heart.\n\nThen she was born\u2014\nHer first cries, \nSweet babbling sounds\u2014\nA melody, a harmony,\nA song I never knew I needed.\n\nAnd then, there is you\u2014\nMy women, my love,\nThe fortune of an unfortune man,\nThe one who fills my world with care,\nWith love, with unshaken affection.\n\nI need you more than I need myself\u2014\nWithout you, I am nothing.\nI want you by my side in every moment.\nNo words of gratitude can measure,\n\nNo Affirmations can ensure\u2014\nHow much you mean to me.\n\nAnd now, I\u2019m the happiest man alive\u2014\nTwo fortunes, two fulfilled wishes,\nDouble love, double warmth,\nFrom you and your little reflection\u2014\nTwo daughters.",
    "emotion": "passion",
    "depth": 0.45,
    "theme": "Love & Romance",
    "volume": "Volume I: Echoes of the Heart"
  },
  {
    "id": 87,
    "title": "Unmasked",
    "author": "dhanavan",
    "preview": "Unmasked I wore my silence like armour,...",
    "content": "Unmasked\nI wore my silence like armour,\nlearned the language of holding it in\u2014\nbecause love once felt like a blade\ndisguised as a whisper.\n\nI built walls, not to keep out love,\nbut to keep in what little of me was left.\nStill\u2014\nin the quiet,\nI read, I healed, I listened.\nTo poetry. To psychology. To me.\n\nI am not cold.\nI am cautious.\nNot heartless\u2014just healing.\nI gave love freely\nand asked only for its echo.\nThat is not a curse. That is truth.\n\nLet the world think I\u2019m fine.\nBut the mirror knows the weight.\nThe pillow knows the flood.\nThe night knows the war.\n\nBut I\u2014\nI know the dawn.\nAnd I am walking toward it,\nunmasked,\nunafraid,\nand finally,\nwhole.",
    "emotion": "passion",
    "depth": 0.48,
    "theme": "Love & Romance",
    "volume": "Volume I: Echoes of the Heart"
  },
  {
    "id": 88,
    "title": "Unromantic Romance",
    "author": "dhanavan",
    "preview": "Unromantic Romance After a long day,...",
    "content": "Unromantic Romance\nAfter a long day,\nI returned home,\nWalked straight to my room\nLying lifeless on my bed,\nStaring at the ceiling.\n\nMy mind echoes,\nThe unfading touch of nightmares,\nBittersweet moments\nFrom the months spent with you.\n\nNo expectations,\nYet still\u2014can\u2019t believe.\nAssumptions failed.\nYou chose someone else,\nAfter making me believe\nI was the one\u2014\nGifted, chosen, admired.\nIn the end, I wasn\u2019t.\n\nWhat made me chase you, choose you?\nWhen I was doing fine on my own?\nWhy did you appear in my view?\nWhy those windows, those stares?\nWhy those smiles, those waving hands?\n\nYou came like a star,\nAnd disappeared \nLike ashes in the wind.\n\nYou left me in a void;\nA hollow space of hopeless hope.\nAn unromantic romance,\nDistance,\nDevouring me silently.\n\nMy emotions\u2014my own.\nNever your responsibility.\nHow? Yet somehow?\nYour inconvenience, your guilt,\nBecame my burden.\n\nI don\u2019t want you back.\nStay where you are\u2014\nLeft in an ocean of sharks,\nDon\u2019t bother wondering\nHow I make it to shore?\n\nI chose peace. \nI chose solitude.\nI chose me\u2014\nOver you.",
    "emotion": "serenity",
    "depth": 0.33,
    "theme": "Nature & Beauty",
    "volume": "Volume II: Nature's Breath"
  },
  {
    "id": 89,
    "title": "Unspoken Love",
    "author": "dhanavan",
    "preview": "Unspoken Love I\u2019m not awkward to say this\u2014...",
    "content": "Unspoken Love\nI\u2019m not awkward to say this\u2014\nYes, I fell in love with him.\nYes, he's silent, his world without words,\nBut that\u2019s what speaks to me.\n\nHe loves in a different way,\nIn a language that reaches my soul.\nI fell in love with every sign\nHis hands shape softly in the air.\n\nThe way his fingers dance,\nPainting my sky in hues so vivid\u2014\nHow I wish to be his muse.\n\nHis love language is touch;\nHis hands tremble as he calls me.\nHe needs no words\u2014\nOur eyes speak what sounds never could.\n\nHe holds the world with quiet calm,\nEmotions in waves, unspoken, strong.\nHis laughter, a gentle revelation,\nMakes me love him more than he\u2019ll know.\n\nIn him, I've found a soul so pure,\nA heart untouched by pride or malice.\n\nEach day, I pray to God above,\nTo hold his hand, forever in love.",
    "emotion": "passion",
    "depth": 1,
    "theme": "Love & Romance",
    "volume": "Volume I: Echoes of the Heart"
  },
  {
    "id": 90,
    "title": "Untold Love",
    "author": "dhanavan",
    "preview": "Untold Love My friends let slip the truth untold;...",
    "content": "Untold Love\nMy friends let slip the truth untold;\nMy love for her my heart did hold;\nYet little did I ever know;\nHer heart, too, hid a tender glow;\n\nOur love,stars behind night's veil;\nA moonlight tale, serene and frail.\nLike raindrops freshening the earth anew,\nOr rainbow hues in softest view,\nMy love shines, a gradient gleam,\nAlive and bright in a quiet dream.\n\nWith care, like tending a flower\u2019s bloom,\nThrough every season, heart in bloom,\nWaiting for petals to unfold,\nA love too deep to leave untold.",
    "emotion": "passion",
    "depth": 1,
    "theme": "Love & Romance",
    "volume": "Volume I: Echoes of the Heart"
  },
  {
    "id": 91,
    "title": "We and tea",
    "author": "dhanavan",
    "preview": "We and tea On a cold evening, with rainfall and a c...",
    "content": "We and tea\nOn a cold evening, with rainfall and a chill breeze,\nThe skies are dusky, and raindrops nourish the warmth.\n\nWe are wrapped under the blanket\nCuddling close, \nWhispering softly to one another,\nOur song played in the background.\nWith cups of tea in our hands,\nThe chill draws us nearer- \nYet holding you feels like the truest warmth.\n\nShadows flicker under the glow of the flame.\nYou and I,\nLost in the safety of each other\u2019s loving arms.",
    "emotion": "passion",
    "depth": 0.37,
    "theme": "Nature & Beauty",
    "volume": "Volume II: Nature's Breath"
  },
  {
    "id": 92,
    "title": "Words They Leave Behind",
    "author": "dhanavan",
    "preview": "Words They Leave Behind When they can't be together...",
    "content": "Words They Leave Behind\nWhen they can't be together,\nThey say\u2014\n'In another lifetime' \n\nWhen they want you,\nThey say\u2014\n'Stay'\n\nWhen they need you,\nThey say\u2014\n'For me..'\n\nWhen they admire you,\nThey say\u2014\n'You are beautiful'\n\nWhen they miss you,\nThey weep for you\u2014\nIn silence, in shadows, in memories too.\n\nWhen they dream of you,\nThey whisper\u2014\n\"If only...\"\n\nWhen they lose you,\nThey carry you\u2014\nIn fragments of moments, in echoes that linger.\n\nAnd when they love you,\nThey say\u2014\n\"Forever.\"",
    "emotion": "mystery",
    "depth": 0.53,
    "theme": "Love & Romance",
    "volume": "Volume I: Echoes of the Heart"
  },
  {
    "id": 93,
    "title": "Writer's Tale",
    "author": "dhanavan",
    "preview": "Writer\u2019s Tale O Beloved,...",
    "content": "Writer\u2019s Tale\nO Beloved,\nO Beloved,\nA writer's love\nIs different.\nIf a writer loves you,\nYou will never die \u2014\nTheir words will melt\nYou down to the core.\nIf the writer wrote Come,\nShe came.\nIf the writer wrote Sit,\nShe sat.\nIf he wrote Lay your head on my shoulder,\nShe rested there.\nHe wrote Sleep,\nAnd she drifted away.\nIf he wrote Lost,\nShe wandered,\nAnd when he wrote Restless,\nShe became uneasy.\nSeeing her pain, he stumbled \u2014 heartache.\nSo he removed less from the word,\nSo she could rest.\nWhen the writer wrote Special,\nShe felt butterflies stir within her.\nWhen he wrote Aim,\nShe chased after him.\nWhen he wrote Love,\nShe fell for him.\nAnd when he wrote Stay,\nShe stayed \u2014 forever.",
    "emotion": "passion",
    "depth": 0.57,
    "theme": "Love & Romance",
    "volume": "Volume I: Echoes of the Heart"
  }
];